# Generated by Django 4.2.25 on 2025-10-03 08:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trattativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=200)),
                ('cliente', models.CharField(max_length=100)),
                ('valore', models.DecimalField(decimal_places=2, help_text='Valore stimato della trattativa', max_digits=10)),
                ('stato', models.CharField(choices=[('Da Contattare', 'Da Contattare'), ('In Corso', 'In Corso'), ('Vinta', 'Vinta'), ('Persa', 'Persa')], default='Da Contattare', max_length=20)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('ultima_modifica', models.DateTimeField(auto_now=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('responsabile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-ultima_modifica'],
            },
        ),
    ]
