# Generated by Django 4.2.25 on 2025-10-03 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trattative', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trattativa',
            name='stato',
            field=models.CharField(choices=[('Da Contattare', 'Da Contattare'), ('Contattato', 'Contattato'), ('Demo', 'Demo'), ('Preventivo Tecnico', 'Preventivo Tecnico'), ('Preventivo Commerciale', 'Preventivo Commerciale'), ('Vinta', 'Vinta'), ('Persa', 'Persa')], default='Da Contattare', max_length=30),
        ),
    ]
