# Generated by Django 4.2.25 on 2025-10-03 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trattative', '0002_alter_trattativa_stato'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=200)),
                ('priorita', models.IntegerField(choices=[(3, 'Urgente'), (2, 'Media'), (1, 'Bassa')], default=2)),
                ('data_scadenza', models.DateField(blank=True, null=True)),
                ('completato', models.BooleanField(default=False)),
                ('assegnato_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to=settings.AUTH_USER_MODEL)),
                ('creato_da', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks_create', to=settings.AUTH_USER_MODEL)),
                ('trattativa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='trattative.trattativa')),
            ],
            options={
                'ordering': ['-priorita', 'data_scadenza'],
            },
        ),
        migrations.CreateModel(
            name='GruppoLavoro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('membri', models.ManyToManyField(related_name='gruppi_lavoro', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Commento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testo', models.TextField()),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('autore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('trattativa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commenti', to='trattative.trattativa')),
            ],
            options={
                'ordering': ['data_creazione'],
            },
        ),
    ]
