# Generated by Django 4.2.25 on 2025-10-03 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trattative', '0003_task_gruppolavoro_commento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trattativa',
            name='responsabile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='trattative', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
