# Generated by Django 4.2.25 on 2025-10-03 17:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trattative', '0004_alter_trattativa_responsabile'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='collaboratori',
            field=models.ManyToManyField(blank=True, related_name='task_collabora', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trattativa',
            name='collaboratori',
            field=models.ManyToManyField(blank=True, related_name='trattative_collabora', to=settings.AUTH_USER_MODEL),
        ),
    ]
